#!/usr/bin/env bash
#
# Copyright 2020 Tymoteusz Blazejczyk
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit on error
set -eo pipefail

function color_red {
    # Print text with red color
    echo -e "\e[1;31m$1\e[0m"
}

function go_build {
    local ARGUMENTS
    local FAILED

    ARGUMENTS=${@:-./...}
    FAILED=0

    if ! go build $ARGUMENTS; then
        color_red "Build failed for $ARGUMENTS"
        FAILED=1
    fi

    return $FAILED
}

go_build $@
