#!/usr/bin/env bash
#
# Copyright 2020 Tymoteusz Blazejczyk
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit on error
set -eo pipefail

git_config_set() {
    touch "${HOME}/.gitconfig" >/dev/null 2>&1 || true

    if command -v git >/dev/null 2>&1; then
        for config in "local" "global" "system"; do
            if ! git config "--${config}" --get "url.${1}.insteadof" >/dev/null 2>&1; then
                git config "--${config}" "url.${1}.insteadOf" "${2}" >/dev/null 2>&1 || true
            fi
        done
    fi
}

go_git() {
    if [ -n "${GITLAB_ACCESS_TOKEN:-}" ]; then
        git_config_set "https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/" "https://gitlab.com/"
    elif [ -n "${CI_JOB_TOKEN:-}" ]; then
        git_config_set "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/" "https://gitlab.com/"
    else
        git_config_set "git@gitlab.com:" "https://gitlab.com/"
    fi
}

go_git
