#!/usr/bin/env bash
#
# Copyright 2020 Tymoteusz Blazejczyk
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit on error
set -eo pipefail

function color_cyan {
    # Print text with cyan color
    echo -e "\e[1;36m$1\e[0m"
}

function color_yellow {
    # Print text with yellow color
    echo -e "\e[1;33m$1\e[0m"
}

function color_green {
    # Print text with green color
    echo -e "\e[1;32m$1\e[0m"
}

function color_red {
    # Print text with red color
    echo -e "\e[1;31m$1\e[0m"
}

function command_exists {
    # Check if provided command exists
    command -v "$1" 2>&1 >/dev/null
}

function go_lint {
    local FORMAT_ARGUMENTS
    local ARGUMENTS
    local FAILED

    # First capture all command line arguments to a separate variable.
    # This will allow to preserve command invocation from unwanted behavior
    ARGUMENTS=${@:-./...}

    # Transform substrings from ... to standard .
    FORMAT_ARGUMENTS=$(echo "$ARGUMENTS" | sed 's/\.\.\././')

    # Initialize failed variable
    FAILED=0

    # Validating Go imports
    if command_exists goimports; then
        local OUTPUT

        if ! command_exists colordiff; then
            color_red "The colordiff tool is not installed"
            exit 1
        fi

        color_cyan "Running the goimports linter..."

        OUTPUT=$(goimports -l $FORMAT_ARGUMENTS || true)

        if [[ -z "$OUTPUT" ]]; then
            color_green "The goimports linter passed"
        else
            color_red "Go imports are not formatted correctly"

            color_cyan "Listing all ill-formatted files:"
            echo "$OUTPUT"

            color_cyan "Detailed formatting differences:"
            goimports -d -e $FORMAT_ARGUMENTS | colordiff
            color_red "The goimports linter failed"
            FAILED=1
        fi
    else
        color_red "The goimports tool is not installed"
    fi

    # Go source files formatting
    if command_exists gofmt; then
        local OUTPUT

        if ! command_exists colordiff; then
            color_red "The colordiff tool is not installed"
            exit 1
        fi

        color_cyan "Running the gofmt linter..."

        OUTPUT=$(gofmt -l $FORMAT_ARGUMENTS || true)

        if [[ -z "$OUTPUT" ]]; then
            color_green "The gofmt linter passed"
        else
            color_red "Go source files are not formatted correctly"

            color_cyan "Listing all ill-formatted files:"
            echo "$OUTPUT"

            color_cyan "Detailed formatting differences:"
            gofmt -d -e $FORMAT_ARGUMENTS | colordiff
            color_red "The gofmt linter failed"
            FAILED=1
        fi
    else
        color_red "The gofmt tool is not installed"
    fi

    # Go source files linting with the revive tool
    if command_exists revive; then
        local OUTPUT
        local OPTIONS

        OPTIONS="-formatter friendly"

        if [[ -f "revive.toml" ]]; then
            OPTIONS="$OPTIONS -config revive.toml"

        elif [[ -f ".revive.toml" ]]; then
            OPTIONS="$OPTIONS -config .revive.toml"

        elif [[ -f "/usr/local/go/revive.toml" ]]; then
            OPTIONS="$OPTIONS -config /usr/local/go/revive.toml"
        fi

        color_cyan "Running the revive linter..."

        if revive $OPTIONS $ARGUMENTS; then
            color_green "The revive linter passed"
        else
            color_red "The revive linter failed"
            FAILED=1
        fi
    else
        color_red "The revive tool is not installed"
    fi

    # Go source files linting with the golangci-lint tool
    if command_exists golangci-lint; then
        local OUTPUT
        local OPTIONS

        OPTIONS="--color always"

        if [[ -f ".golangci.yml" ]]; then
            OPTIONS="$OPTIONS --config .golangci.yml"

        elif [[ -f "/usr/local/go/.golangci.yml" ]]; then
            OPTIONS="$OPTIONS --config /usr/local/go/.golangci.yml"
        fi

        color_cyan "Running the golangci-lint linter..."

        if golangci-lint run $OPTIONS $ARGUMENTS; then
            color_green "The golangci-lint linter passed"
        else
            color_red "The golangci-lint linter failed"
            FAILED=1
        fi
    else
        color_red "The golangci-lint tool is not installed"
    fi

    # Go source files linting with the golint tool
    if command_exists golint; then
        local OUTPUT

        color_cyan "Running the golint linter..."

        if golint $ARGUMENTS; then
            color_green "The golint linter passed"
        else
            color_red "The golint linter failed"
            FAILED=1
        fi
    else
        color_red "The golint tool is not installed"
    fi

    # Go source files linting with the errcheck tool
    if command_exists errcheck; then
        local OUTPUT
        local OPTIONS

        OPTIONS="-ignoregenerated -blank -asserts"

        if [[ -f "./errcheck_excludes.txt" ]]; then
            OPTIONS="$OPTIONS -exclude errcheck_excludes.txt"
        fi

        color_cyan "Running the errcheck linter..."

        if errcheck $OPTIONS $ARGUMENTS; then
            color_green "The errcheck linter passed"
        else
            color_red "The errcheck linter failed"
            FAILED=1
        fi
    else
        color_red "The errcheck tool is not installed"
    fi

    return $FAILED
}

go_lint $@
